services:
  app:
    image: ${DOCKERHUB_USERNAME}/captain:${IMAGE_TAG:-latest}
    container_name: subnetwork_system_prod
    depends_on:
      postgres_prod:
        condition: service_healthy
      clickhouse_prod:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env.prod
    restart: unless-stopped
  postgres_prod:
    image: postgres:15
    container_name: subnetwork_system_database_prod
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./sql/seed:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $POSTGRES_USER -d $POSTGRES_DB"]
      interval: 5s
      timeout: 5s
      retries: 5
  clickhouse_prod:
    image: clickhouse/clickhouse-server:latest
    container_name: subnetwork_system_clickhouse_prod
    environment:
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
    ports:
      - "127.0.0.1:8123:8123"
      - "127.0.0.1:9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - ./sql/clickhouse:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "clickhouse-client", "--user", "${CLICKHOUSE_USER:-default}", "--password", "${CLICKHOUSE_PASSWORD:-}", "--query", "SELECT 1"]
      interval: 5s
      timeout: 5s
      retries: 5  

volumes:
  postgres_data:
  clickhouse_data:
